name: build

on:
  push:
    paths:
      - .github/workflows/build.yml
      - packages/**/*/package.json
      - packages/**/*/src/*
      - packages/**/*/src/**/*
      - yarn.lock
    pull_request:
      branches:
        - stable
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        node:
          - 15.x

    name: test node@${{matrix.node}}/${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run test container
        run: docker-compose up --exit-code-from bud
